# Configuration settings in this file should be ordered
# alphabetically.
---
copyright: >
  <a href="https://creativecommons.org/licenses/by-sa/4.0/">
  <img src="https://mirrors.creativecommons.org/presskit/buttons/80x15/svg/by-sa.svg"/>
  </a>
edit_uri: ./edit/main/docs
plugins:
  - git-authors:
      enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: true
      fallback_to_build_date: false
      locale: en
      timezone: Etc/UTC
      type: iso_date
  - htmlproofer:
      raise_error: true
      validate_external_urls: true
  - macros
  - search
repo_url: https://github.com/citynetwork/docs
site_name: "Replace This Placeholder Before Making This Public"
theme:
  custom_dir: theme
  icon:
    repo: fontawesome/brands/github
  name: material
